SC_WIDTH = 1024                          # Ширина экрана
SC_HEIGHT = 768                         # Высота экрана
SC_RESOLUTION = (SC_WIDTH, SC_HEIGHT)   # Разрешение экрана
SC_BACKGROUND = (0, 0, 0)               # Задний фон
SC_FULLSCREEN = False
SC_FPS = 50                             # Ограничитель кадров
SC_CENTER_X = int(SC_WIDTH / 2)         # Центр экрана по оси X
SC_CENTER_Y = int(SC_HEIGHT / 2)        # Центр экрана по оси Y
SC_CENTER = (SC_CENTER_X, SC_CENTER_Y)  # Центр экрана по обоим осям
TRANSPARENT_COLOR = (0, 255, 0)         # Прозрачный цвет
